title: 12urenloop Documentation
description: This site should help you give an overview of things that exist in relation to organizing the yearly 12urenloop and setting up the counting system.
remote_theme: pmarsceill/just-the-docs
baseurl: /docs.12urenloop
